const wordbookActionType = {
  GET_WORDBOOK_PENDING: "GET_WORDBOOK_PENDING",
  GET_WORDBOOK_FULFILLED: "GET_WORDBOOK_FULFILLED",
  GET_WORDBOOK_REJECTED: "GET_WORDBOOK_REJECTED",
  POST_TOPIC_FULFILLED: "POST_TOPIC_FULFILLED",
  DELETE_TOPIC_FULFILLED: "DELETE_TOPIC_FULFILLED",
  PATCH_TOPIC_FULFILLED: "PATCH_TOPIC_FULFILLED",
  POST_WORD_FULFILLED: "POST_WORD_FULFILLED",
  DELETE_WORD_FULFILLED: "DELETE_WORD_FULFILLED",
  PATCH_WORD_FULFILLED: "PATCH_WORD_FULFILLED",
};

export default wordbookActionType;
