const wordbookActionType = {
  GET_WORDBOOK_PENDING: "GET_WORDBOOK_PENDING",
  GET_WORDBOOK_FULFILLED: "GET_WORDBOOK_FULFILLED",
  GET_WORDBOOK_REJECTED: "GET_WORDBOOK_REJECTED",
  POST_TOPIC_PENDING: "POST_TOPIC_PENDING",
  POST_TOPIC_FULFILLED: "POST_TOPIC_FULFILLED",
  POST_TOPIC_REJECTED: "POST_TOPIC_REJECTED",
  DELETE_TOPIC_PENDING: "DELETE_TOPIC_PENDING",
  DELETE_TOPIC_FULFILLED: "DELETE_TOPIC_FULFILLED",
  DELETE_TOPIC_REJECTED: "DELETE_TOPIC_REJECTED",
  PATCH_TOPIC_PENDING: "PATCH_TOPIC_PENDING",
  PATCH_TOPIC_FULFILLED: "PATCH_TOPIC_FULFILLED",
  PATCH_TOPIC_REJECTED: "PATCH_TOPIC_REJECTED",
  //
  GET_CURRENT_WORDS: "GET_CURRENT_WORDS",
  POST_WORD_PENDING: "POST_WORD_PENDING",
  POST_WORD_FULFILLED: "POST_WORD_FULFILLED",
  POST_WORD_REJECTED: "POST_WORD_REJECTED",
  DELETE_WORD_PENDING: "DELETE_WORD_PENDING",
  DELETE_WORD_FULFILLED: "DELETE_WORD_FULFILLED",
  DELETE_WORD_REJECTED: "DELETE_WORD_REJECTED",
  PATCH_WORD_PENDING: "PATCH_WORD_PENDING",
  PATCH_WORD_FULFILLED: "PATCH_WORD_FULFILLED",
  PATCH_WORD_REJECTED: "PATCH_WORD_REJECTED",
};

export default wordbookActionType;
